### ISSUE TITLE
listen method not define error

### ISSUE THREAD

**Issue by NAME-NikhilPatil** [iampawan/VxState#1]
velocity-x version
 velocity_x: ^2.1.0

 VxState.listen(context, to: [AddMutation]);
yaha ye error message aa raha he:
The method 'listen' isn't defined for the type 'VxState'.
Try correcting the name to the name of an existing method, or defining a method named 'listen'.

**Comment by ayyysh04** [comment]
VxState.listen() has been discontinued.
**Use VxState.watch()**
