### ISSUE TITLE
The method 'listen' isn't defined for the type 'VxState'. 

### ISSUE THREAD

**Issue by Dinesh-choudhary-Wow** [iampawan/VxState#2]
The method 'listen' isn't defined for the type 'VxState'.
Try correcting the name to the name of an existing method, or defining a method named 'listen'.
from your flutter video https://youtu.be/j-LOab_PzzU
day 27 when we put listen in add_to_cart.dart file it was displaying the above issue.
and may this error is in the new version or vxstate
![Screenshot (27)](https://user-images.githubusercontent.com/97819644/158793350-22625815-831a-4470-8942-290e7b3be09a.png)
.

**Comment by iampawan** [comment]
Use .watch()
