### ISSUE TITLE
Passing data to a Mutation

### ISSUE THREAD

**Issue by tyshantprince** [iampawan/VxState#3]
I am trying to send data from the UI back to the store and use it in a Mutation, is that possible?

**Comment by nathantaal** [comment]
I would also like to know that

**Comment by nathantaal** [comment]
Don't know if this is the best way @tyshantprince , but you could do it like this:

```
class AddItem extends VxMutation<MainStore> {
  Item item;
  AddItem(this.item);

  @override
  perform() => {
    store?.items.add(item),
  };
}
```

**Comment by iampawan** [comment]
Yes you can do this
