### ISSUE TITLE
VxStateWidgetBuilder store type doesn't affect builder store type

### ISSUE THREAD

**Issue by LuisReyes98** [iampawan/VxState#5]
In the VxStateWidgetBuilder T is the store type and it is not being used in the method, It is a small change that allows the builder in the widgets in vxbuilder and vxconsumer to nativelly use the type.
The change can be seen more clearly in this pull request https://github.com/iampawan/VxState/pull/4

**Comment by iampawan** [comment]
Fixed with v2.3.0
